Started logging messages at Thu Aug 29 01:15:36 2024
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 108 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 57
Info:            Created 
Info:        Working on 79
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 77
Info:            Created 
Info:        Working on 78
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 106
Info:            Created 
Info:        Working on 147
Info:            Created 
Info:        Working on 148
Info:            Created 
Info:        Working on 184
Info:            Created 
Info:        Working on 255
Info:            Created 
Info:        Working on 355
Info:            Created 
Info:        Working on 461
Info:            Created 
Info:        Working on 595
Info:            Created 
Info:        Working on 775
Info:            Created 
Info:        Working on 975
Info:            Created 
Info:        Working on 1198
Info:            Created 
Info:        Working on 1415
Info:            Created 
Info:        Working on 1610
Info:            Created 
Info:        Working on 1709
Info:            Created 
Info:        Working on 1708
Info:            Created 
Info:        Working on 1775
Info:            Created 
Info:        Working on 1672
Info:            Created 
Info:        Working on 1300
Info:            Created 
Info:        Working on 1665
Info:            Created 
Info:        Working on 1635
Info:            Created 
Info:        Working on 1468
Info:            Created 
Info:        Working on 1258
Info:            Created 
Info:        Working on 1039
Info:            Created 
Info:        Working on 831
Info:            Created 
Info:        Working on 634
Info:            Created 
Info:        Working on 491
Info:            Created 
Info:        Working on 379
Info:            Created 
Info:        Working on 273
Info:            Created 
Info:        Working on 196
Info:            Created 
Info:        Working on 170
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 123
Info:            Created 
Info:        Working on 153
Info:            Created 
Info:        Working on 29
Info:            Created 
Info:        Working on 42
Info:            Created 
Info:        Working on 320
Info:            Created 
Info:        Working on 428
Info:            Created 
Info:        Working on 432
Info:            Created 
Info:        Working on 326
Info:            Created 
Info:        Working on 61
Info:            Created 
Info:        Working on 311
Info:            Created 
Info:        Working on 312
Info:            Created 
Info:        Working on 415
Info:            Created 
Info:        Working on 419
Info:            Created 
Info:        Working on 83
Info:            Created 
Info:        Working on 113
Info:            Created 
Info:        Working on 684
Info:            Created 
Info:        Working on 884
Info:            Created 
Info:        Working on 885
Info:            Created 
Info:        Working on 687
Info:            Created 
Info:        Working on 157
Info:            Created 
Info:        Working on 521
Info:            Created 
Info:        Working on 212
Info:            Created 
Info:        Working on 152
Info:            Created 
Info:        Working on 677
Info:            Created 
Info:        Working on 208
Info:            Created 
Info:        Working on 878
Info:            Created 
Info:        Working on 290
Info:            Created 
Info:        Working on 1090
Info:            Created 
Info:        Working on 1091
Info:            Created 
Info:        Working on 400
Info:            Created 
Info:        Working on 723
Info:            Created 
Info:        Working on 724
Info:            Created 
Info:        Working on 515
Info:            Created 
Info:        Working on 1498
Info:            Created 
Info:        Working on 1499
Info:            Created 
Info:        Working on 668
Info:            Created 
Info:        Working on 1112
Info:            Created 
Info:        Working on 1359
Info:            Created 
Info:        Working on 865
Info:            Created 
Info:        Working on 1073
Info:            Created 
Info:        Working on 714
Info:            Created 
Info:        Working on 715
Info:            Created 
Info:        Working on 550
Info:            Created 
Info:        Working on 1551
Info:            Created 
Info:        Working on 1705
Info:            Created 
Info:        Working on 719
Info:            Created 
Info:        Working on 1703
Info:            Created 
Info:        Working on 1704
Info:            Created 
Info:        Working on 920
Info:            Created 
Info:        Working on 1341
Info:            Created 
Info:        Working on 1108
Info:            Created 
Info:        Working on 1138
Info:            Created 
Info:        Working on 1374
Info:            Created 
Info:        Working on 1348
Info:            Created 
Info:        Working on 1369
Info:            Created 
Info:        Working on 1536
Info:            Created 
Info:        Working on 1697
Info:            Created 
Info:        Working on 1750
Info:            Created 
Info:        Working on 1645
Info:            Created 
Info:        Working on 1757
Info:            Created 
Info:        Working on 1834
Info:            Created 
Info:        Working on 1805
Info:            Created 
Info:        Working on 1815
Info:            Created 
Info:        Working on 1423
Info:            Created 
Info:        Working on 1128
Info:            Created 
Info:        Working on 1418
Info:            Created 
Info:        Working on 1267
Info:            Created 
Info:        Working on 1479
Info:            Created 
Info:        Working on 1264
Info:            Created 
Info:        Working on 1210
Info:            Created 
Info:        Working on 992
Info:            Created 
Info:        Working on 1222
Info:            Created 
Info:        Working on 1744
Info:            Created 
Info:        Working on 1620
Info:            Created 
Info:        Working on 1441
Info:            Created 
Info:        Working on 1618
Info:            Created 
Info:        Working on 1446
Info:            Created 
Info:        Working on 1604
Info:            Created 
Info:        Working on 1605
Info:            Created 
Info:        Working on 1622
Info:            Created 
Info:        Working on 1276
Info:            Created 
Info:        Working on 1317
Info:            Created 
Info:        Working on 1101
Info:            Created 
Info:        Working on 1052
Info:            Created 
Info:        Working on 1268
Info:            Created 
Info:        Working on 1273
Info:            Created 
Info:        Working on 1048
Info:            Created 
Info:        Working on 1456
Info:            Created 
Info:        Working on 1023
Info:            Created 
Info:        Working on 1270
Info:            Created 
Info:        Working on 988
Info:            Created 
Info:        Working on 794
Info:            Created 
Info:        Working on 1004
Info:            Created 
Info:        Working on 786
Info:            Created 
Info:        Working on 664
Info:            Created 
Info:        Working on 663
Info:            Created 
Info:        Working on 994
Info:            Created 
Info:        Working on 645
Info:            Created 
Info:        Working on 841
Info:            Created 
Info:        Working on 640
Info:            Created 
Info:        Working on 473
Info:            Created 
Info:        Working on 606
Info:            Created 
Info:        Working on 467
Info:            Created 
Info:        Working on 286
Info:            Created 
Info:        Working on 285
Info:            Created 
Info:        Working on 204
Info:            Created 
Info:        Working on 368
Info:            Created 
Info:        Working on 261
Info:            Created 
Info:        Working on 363
Info:            Created 
Info:        Working on 500
Info:            Created 
Info:        Working on 475
Info:            Created 
Info:        Working on 390
Info:            Created 
Info:        Working on 385
Info:            Created 
Info:        Working on 280
Info:            Created 
Info:        Working on 393
Info:            Created 
Info:        Working on 506
Info:            Created 
Info:        Working on 659
Info:            Created 
Info:        Working on 860
Info:            Created 
Info:        Working on 855
Info:            Created 
Info:        Working on 890
Info:            Created 
Info:        Working on 1069
Info:            Created 
Info:        Working on 1061
Info:            Created 
Info:        Working on 894
Info:            Created 
Info:        Working on 1283
Info:            Created 
Info:        Working on 1105
Info:            Created 
Info:        Working on 1319
Info:            Created 
Info:        Working on 1211
Info:            Created 
Info:        Working on 983
Info:            Created 
Info:        Working on 1205
Info:            Created 
Info:        Working on 1426
Info:            Created 
Info:        Working on 1585
Info:            Created 
Info:        Working on 1724
Info:            Created 
Info:        Working on 1579
Info:            Created 
Info:        Working on 1628
Info:            Created 
Info:        Working on 1612
Info:            Created 
Info:        Working on 1338
Info:            Created 
Info:        Working on 1531
Info:            Created 
Info:        Working on 1134
Info:            Created 
Info:        Working on 1344
Info:            Created 
Info:        Working on 733
Info:            Created 
Info:        Working on 440
Info:            Created 
Info:        Working on 564
Info:            Created 
Info:        Working on 738
Info:            Created 
Info:        Working on 444
Info:            Created 
Info:        Working on 728
Info:            Created 
Info:        Working on 571
Info:            Created 
Info:        Working on 741
Info:            Created 
Info:        Working on 935
Info:            Created 
Info:        Working on 1802
Info:            Created 
Info:        Working on 1779
Info:            Created 
Info:        Working on 1778
Info:            Created 
Info:        Working on 1825
Info:            Created 
Info:        Working on 1162
Info:            Created 
Info:        Working on 1506
Info:            Created 
Info:        Working on 1509
Info:            Created 
Info:        Working on 1310
Info:            Created 
Info:        Working on 656
Info:            Created 
Info:        Working on 857
Info:            Created 
Info:        Working on 814
Info:            Created 
Info:        Working on 622
Info:            Created 
Info:        Working on 1179
Info:            Created 
Info:        Working on 817
Info:            Created 
Info:        Working on 1027
Info:            Created 
Info:        Working on 1245
Info:            Created 
Info:        Working on 1460
Info:            Created 
Info:        Working on 1631
Info:            Created 
Info:        Working on 1438
Info:            Created 
Info:        Working on 537
Info:            Created 
Info:        Working on 241
Info:            Created 
Info:        Working on 960
Info:            Created 
Info:        Working on 961
Info:            Created 
Info:        Working on 1182
Info:            Created 
Info:        Working on 342
Info:            Created 
Info:        Working on 1013
Info:            Created 
Info:        Working on 448
Info:            Created 
Info:        Working on 574
Info:            Created 
Info:        Working on 1575
Info:            Created 
Info:        Working on 1576
Info:            Created 
Info:        Working on 1717
Info:            Created 
Info:        Working on 1695
Info:            Created 
Info:        Working on 745
Info:            Created 
Info:        Working on 1694
Info:            Created 
Info:        Working on 1333
Info:            Created 
Info:        Working on 939
Info:            Created 
Info:        Working on 1165
Info:            Created 
Info:        Working on 1233
Info:            Created 
Info:        Working on 1231
Info:            Created 
Info:        Working on 1741
Info:            Created 
Info:        Working on 1449
Info:            Created 
Info:        Working on 1625
Info:            Created 
Info:        Working on 1010
Info:            Created 
Info:        Working on 1154
Info:            Created 
Info:        Working on 1363
Info:            Created 
Info:        Working on 1059
Info:            Created 
Info:        Working on 852
Info:            Created 
Info:        Working on 1772
Info:            Created 
Info:        Working on 1773
Info:            Created 
Info:        Working on 1824
Info:            Created 
Info:        Working on 1822
Info:            Created 
Info:        Working on 1065
Info:            Created 
Info:        Working on 1823
Info:            Created 
Info:        Working on 1837
Info:            Created 
Info:        Working on 1280
Info:            Created 
Info:        Working on 1483
Info:            Created 
Info:        Working on 1649
Info:            Created 
Info:        Working on 1676
Info:            Created 
Info:        Working on 1738
Info:            Created 
Info:        Working on 1739
Info:            Created 
Info:        Working on 1806
Info:            Created 
Info:        Working on 1807
Info:            Created 
Info:        Working on 1188
Info:            Created 
Info:        Working on 710
Info:            Created 
Info:        Working on 914
Info:            Created 
Info:        Working on 1832
Info:            Created 
Info:        Working on 1833
Info:            Created 
Info:        Working on 1095
Info:            Created 
Info:        Working on 1314
Info:            Created 
Info:        Working on 1513
Info:            Created 
Info:        Working on 1679
Info:            Created 
Info:        Working on 1781
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 0.000134539
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Thu Aug 29 01:15:37 2024
